/** @file

  Platform Configuration C Struct Header File.

  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php.

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __CONFIG_DATA_COMMON_STRUCT_H__
#define __CONFIG_DATA_COMMON_STRUCT_H__

#pragma pack(1)


#define  CDATA_GEN_TAG                   0x010
#define  CDATA_PLAT_NAME_TAG             0x070
#define  CDATA_PLATFORMID_TAG            0x0F0


typedef struct {

/**  Platform Name
  Specify the platform name, a maximum of 8 characters
**/
  UINT64                      PlatformName;

} PLAT_NAME_CFG_DATA;


typedef struct {

/**  Debug Print Level
  Specify debug print level
**/
  UINT32                      DebugPrintLevel;

/**  Payload ID
  Specify payload ID string. Empty will boot default payload. Otherwise, boot specified
  payload ID in multi-payload binary.
**/
  UINT32                      PayloadId;

/**  OS Crash Memory Size
  Specify reserved memory size for OS to save OS crash data. The reserved memory address
  should be same across reset.
   0:0MB, 1:4MB, 2:8MB, 3:16MB, 4:32MB, 5:64MB
**/
  UINT8                       OsCrashMemorySize;

/**  Enable Crash Mode
  Enable/Disable Crash Mode. Boot into Crash OS only when crash mode is enabled.
  $EN_DIS
**/
  UINT8                       EnableCrashMode;

/**  RpmbKeyProvisioning
  Enable or disable Rpmb Key Provisioning
  $EN_DIS
**/
  UINT8                       RpmbKeyProvisioning;

/** 
**/
  UINT8                       Reserved;

} GEN_CFG_DATA;


#pragma pack()

#endif
