/** @file

  Platform Configuration C Struct Header File.

  Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php.

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __CONFIG_DATA_STRUCT_H__
#define __CONFIG_DATA_STRUCT_H__

#pragma pack(1)


#define  CDATA_MEMORY_TAG                0x180
#define  CDATA_SILICON_TAG               0x200
#define  CDATA_PLATFORM_TAG              0x280


typedef struct {

/**  Payload ID
  Specify payload ID
**/
  UINT32                      PayloadId;

} PLATFORM_CFG_DATA;


typedef struct {

/**  Memory Test 1
  Memory Test 1
**/
  UINT32                      MemTest1;

} MEMORY_CFG_DATA;


typedef struct {

/**  Silicon Test 1
  Silicon Test 1
**/
  UINT32                      SiliconTest1;

} SILICON_CFG_DATA;


#pragma pack()

#endif
